name: YuukiPS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: YuukiPS
        path: /home/runner/work/YuukiPS Launcher/bin/Release/net6.0-windows
